### ISSUE TITLE
这就是强者的世界吗？面向数据编程受教了

### ISSUE THREAD

**Issue by doutv** [justarandomstring/2020-Huawei-Code-Craft#1]

**Comment by justarandomstring** [comment]
事实上，对于不同的图类型，不同的算法优劣程度是不同的：比如对于随机图，先反着遍历 3 层获取信息用于后续的剪枝比较优；而对于完全图，直接 dfs 7 层更优。因此如果线上没有提供充足种类、足够复杂的图，而是只提供了一个具有极特殊性质的图，面向数据编程是寻求更优分数的被迫选择。

我并不喜欢也不希望面向数据编程，但是在初赛的客观条件下，面向数据编程是内卷的必然结果：仅”跳过大于等于5W的点“这一个微小变化，可以让代码快 10%，如果你身为差点晋级的选手，是否愿意冒这个险呢（在官方最后一天发出声明之前）？在没有足够清晰的规则的支持下，”劣币驱逐良币“的发生只能是必然。

顺便提一下让比赛更加合理的个人观点：

避免这种问题的最好方法是主办方精心构造多种不同模式的图，使数据”没有空子可钻“，进而筛选出最能解决一般性问题的做法；而绝非通过人为的规定，强行规定选手”我数据有漏洞，但是你别钻“。

但凡加入”人为检查代码“的因素，就一定存在”漏判、误判“的可能性（事实上，我的队友在热身赛时就曾被误判，被删除了代码）。”人为检查代码“还会出现规则细节不明确的问题，就拿初赛举例：假设不允许我们 ```if (value >= 50000) continue; ```，那是否允许我们：

1. 如果入度或出度为 0，直接跳过。
2. 如果当前点所在强连通分量大小小于3，直接跳过。
3. 如果我看这个点不顺眼，把它跳过。

选手无法通过一句简单的”必须分析所有数据“来知道上述做法是否合法。

因此，使数据尽可能的”无懈可击“才是解决一切”乱搞算法“的根本途径。加入人工审查，只是拆了东墙补西墙，又挖了一个另外的坑，可能会带来更多的问题。

**Comment by doutv** [comment]
谢谢你的回答，我真的从中学到了不少。（没有嘲讽的意思）
我关issue了。
